# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'facebook-demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for facebook-demo

  pod "FBSDKCoreKit", '5.6.0'
  pod "FBSDKLoginKit", '5.6.0'
  pod "FBSDKShareKit", '5.6.0'
  
  target 'facebook-demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'facebook-demoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
